monolog:
    channels:
        - deprecation  # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - conversion_logger
        - request_response_logger

    handlers:
        # Log rotation for the conversion_logger (defined globally)
        conversion_logger:
            type: rotating_file
            path: "%kernel.logs_dir%/video_conversion.log"  # Path to the conversion logs
            level: debug
            max_files: 7  # Retain logs for 7 days
            channels: [ 'conversion_logger' ]
            formatter: monolog.formatter.line
        request_response_logger:
            type: rotating_file
            path: "%kernel.logs_dir%/request_response.log"  # Path to the conversion logs
            level: debug
            max_files: 2
            channels: [ 'request_response_logger' ]
            formatter: monolog.formatter.line

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
