nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Allow all origins
        allow_headers: ['*']  # Allow all headers
        allow_methods: ['*']  # Allow all HTTP methods (GET, POST, PUT, DELETE, etc.)
        expose_headers: []  # No specific headers to expose
        max_age: 3600  # Cache preflight request for 1 hour

    # You can also define rules for specific paths, if needed:
    paths:
        '^/':  # Allow CORS for all paths
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            allow_credentials: true
