# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: App\Security\JwtCookieAuthenticationSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        refresh:
            pattern: ^/api/refresh
            stateless: true
            custom_authenticators:
                - App\Security\RefreshTokenAuthenticator

        logout:
            pattern: ^/api/logout
            stateless: true
            security: false  # Disable authentication for this path

        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\JwtCookieOrHeaderAuthenticator
#            jwt:
#                authenticator: App\Security\JwtCookieOrHeaderAuthenticator

    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }